language: julia

julia:
  - nightly
  - 1.1

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; import MapperMDS; cd(joinpath(dirname(pathof(MapperMDS)), ".."));Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
